
import bstproject.BSTobject;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shreyasshukla
 */
public class gui extends javax.swing.JFrame 
{

    /**
     * Creates new form gui
     */
    public static BSTobject<String,String> tree = new BSTobject<String,String>();
    public static BSTobject<String,String> tree1 = new BSTobject<String,String>();
    
    public gui() throws FileNotFoundException {
        initComponents();
        treeTextArea.setEditable(false);
        readFromTextFile();
         
         displayTree();

    }

    private void displayTree()
    {
         treeTextArea.setText("");
         String treeDisplay = tree.toString();
         treeTextArea.setText(treeDisplay);
         
    }
    
     private void displayTreeTestCase()
    {
         treeTextArea.setText("");
         String treeDisplay = tree1.toString();
         treeTextArea.setText(treeDisplay);
         
    }
    
    private void readFromTextFile() throws FileNotFoundException
    {
        Scanner in = new Scanner(new File("textFile.txt"));
        while(in.hasNext())
        {
            String temp = in.nextLine();
            String [] values = temp.split(",");
            String postalCode = values[0];
            String address = values[1];
            tree.add(postalCode,address);
        }
    }
    private void readFromTestCase() throws FileNotFoundException
    {
        Scanner in = new Scanner(new File("testCaseOne.txt")); // default tree for start
        Scanner sc = new Scanner(new File("PostalSector.txt")); // postals values first two digits
        Scanner hs = new Scanner(new File("AddressLoc.txt")); // Names of address
       
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        treeTextArea1 = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTextArea = new javax.swing.JTextArea();

        treeTextArea1.setColumns(20);
        treeTextArea1.setRows(5);
        jScrollPane2.setViewportView(treeTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("ADD");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        treeTextArea.setColumns(20);
        treeTextArea.setRows(5);
        jScrollPane1.setViewportView(treeTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {                                       
      String postalCode = JOptionPane.showInputDialog("Please enter a new postal code ");
      String address = JOptionPane.showInputDialog("Please enter a new address ");
      tree.add(postalCode,address);
      
      displayTree();
        
    }                                      

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
      
        String postalCode = JOptionPane.showInputDialog("Please delete a postal code ");
        tree.delete(postalCode);
        
        displayTree();
        
    }                                            

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
       String postalCode = JOptionPane.showInputDialog("What is the postal code you want to edit ");
       String  newAddress = JOptionPane.showInputDialog("What is the new address you want to replace it with");
       tree.edit(postalCode,newAddress);
        
        displayTree();
    }                                          

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String postalCode = JOptionPane.showInputDialog("What is the postal code you want to search ");
       
        String address = tree.search(postalCode);
        
        if(address != null)
        {
            JOptionPane.showMessageDialog(null, "Valid postal code: " + address);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Postal code not found");
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new gui().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextArea treeTextArea;
    private javax.swing.JTextArea treeTextArea1;
    // End of variables declaration                   
}
