package webscraping;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JOptionPane;
import org.jsoup.*;
import org.jsoup.helper.*;
import org.jsoup.nodes.*;
import org.jsoup.select.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shreyasshukla
 */
public class Gui extends javax.swing.JFrame 
{

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        new Scraper();
        websiteInformation.setEditable(false);
        websiteInformation.setLineWrap(true);
        keyInfoExtracted.setLineWrap(true);
    }

    ArrayList<String> keyWords = new ArrayList<String>();
     String info = "";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keyInfoExtracted = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        websiteInformation = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        websiteButton = new javax.swing.JButton();
        loadTextFile = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        addWords = new javax.swing.JButton();
        saveInformation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Web Scraping");

        keyInfoExtracted.setColumns(20);
        keyInfoExtracted.setRows(5);
        jScrollPane1.setViewportView(keyInfoExtracted);

        jLabel2.setText("Website information");

        websiteInformation.setColumns(20);
        websiteInformation.setRows(5);
        jScrollPane2.setViewportView(websiteInformation);

        jLabel3.setText("Key Informtation Extracted");

        websiteButton.setText("Enter A Website");
        websiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteButtonActionPerformed(evt);
            }
        });

        loadTextFile.setText("Load Text File (Key Words)");
        loadTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTextFileActionPerformed(evt);
            }
        });

        goButton.setText("Go!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        addWords.setText("Add Key Words");
        addWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordsActionPerformed(evt);
            }
        });

        saveInformation.setText("Save Information");
        saveInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(addWords)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveInformation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(websiteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadTextFile)
                        .addGap(26, 26, 26)
                        .addComponent(goButton)
                        .addContainerGap(150, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteButton)
                    .addComponent(goButton)
                    .addComponent(loadTextFile))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addWords)
                    .addComponent(saveInformation))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void websiteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
     
        String websiteUrl = JOptionPane.showInputDialog("What is website url");
        
        websiteUrl = "https://edition.cnn.com/2021/06/07/tech/wwdc-apple-event-roundup/index.html";
      //  websiteUrl = "https://www.nytimes.com/2021/07/09/us/heat-wave-deaths.html";
        Document doc = null;
        
        try {
           doc = Jsoup.connect(websiteUrl).get();
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     Elements tables = doc.getElementsByClass("zn-body__paragraph speakable");
       
       
          for(int a = 0; a < tables.size(); a++)
          {
            Element temp = tables.get(a);
            info = temp.toString();
            websiteInformation.setText(info);
          }
        
      
         websiteInformation.setText(info);
         websiteInformation.setEditable(true);
    }                                             

    private void loadTextFileActionPerformed(java.awt.event.ActionEvent evt) {                                             
      
        Scanner in = null;
        try {
            in = new Scanner(new File("keyTerms.txt"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        while(in.hasNext())
        {
            keyWords.add(in.next());
        }
        

        
    }                                            

    private void addWordsActionPerformed(java.awt.event.ActionEvent evt) {                                         
         String newWord = JOptionPane.showInputDialog("What word do you want to add?");
         keyWords.add(newWord);
    }                                        

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        String temp = "";
//        for(int a = 0; a < keyWords.size(); a++)
//        {
//            temp += keyWords.get(a) + ",";
//        }
//        keyInfoExtracted.setText(temp);

String temp = "";
    
    for(int a = 0; a < keyWords.size(); a++)
    {
        String var = keyWords.get(a).toLowerCase();
        if(info.contains(temp))
        {
            temp += var + ",";
        }
        
    }

 keyInfoExtracted.setText(temp);


        
    }                                        

    private void saveInformationActionPerformed(java.awt.event.ActionEvent evt) {                                                
        websiteInformation.setEditable(false);
        info = websiteInformation.getText().toLowerCase();
        
        
        
    }                                               

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addWords;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea keyInfoExtracted;
    private javax.swing.JButton loadTextFile;
    private javax.swing.JButton saveInformation;
    private javax.swing.JButton websiteButton;
    private javax.swing.JTextArea websiteInformation;
    // End of variables declaration                   
}
